apiVersion: v1
kind: secret
metadata:
  name: postgres-secret
  namespace: banking
type: opaque
stringData:
  POSTGRESS_DB: bankingdb
  POSTGRESS_USER: banking_user
  POSTGRESS_PASSWORD: banking_pass123  